src/cmd/changelog.rs
src/git.rs

fix(changelog): take the date of the tag or last commit of a version

---

.github/workflows/pr.yml
.github/workflows/release.yml

Add a workflow for manual release and pull requests.
Removes the current workflow.

ci: add pr and release workflow

---

src/cli.rs
src/cmd/commit.rs

Adds options for providing the scope, description and body or enable
interactive mode.
Refs: #36

feat(commit): improve commit command

---

src/cmd/version.rs

fix: set right version for unreleased repo

---

src/cli.rs
src/cmd/changelog.rs

feat(changelog): include hidden sections on demand

---

.github/workflows/docker.yml
.github/workflows/pr.yml
.github/workflows/release.yml

No solution yet, so disabling arm64 target
Refs: #62

ci: disable arm64 docker build as it fails

---

src/cli.rs
src/cmd/changelog.rs
src/cmd/check.rs
src/conventional/config.rs
src/git.rs

feat: add merges option for changelog and check command

---

src/conventional/config.rs

fix: use scheme of url if available

---

Cargo.lock
Cargo.toml
src/cmd.rs
src/cmd/changelog.rs
src/cmd/check.rs
src/cmd/commit.rs
src/cmd/version.rs
src/main.rs

Using anyhow it should be easier to find out what was wrong or improve the error message shown to the user.

feat: use anyhow for error handling of commands

---

src/cmd/changelog.rs

The latest tag does not take commits of lower version when limited by `--max-majors`, `--max-minors` or `--max-patches`.
Refs: #92

fix(changelog): correctly render last version if limited by `--max-*`

---

.github/workflows/docker.yml

build: fix arm64 build

---

src/cmd/check.rs

fix(check): read from stdin when rev is not set

---

src/cmd/commit.rs

fix(commit): explicit exit process on ctrlc

---

.github/workflows/release.yml
Cargo.toml

ci: build static debian package

---

src/cmd/changelog.rs

fix(changelog): changelog generator should respect the --prefix flag for unreleased version

---

src/conventional/commits.rs

fix: parse issues in description

---

src/cmd/check.rs

fix(check): check should fail on unrecognized types from stdin

---

src/conventional/config.rs
src/main.rs

fix(check): check should not fail if read from stdin

---

src/cmd/check.rs

fix: stdin return code

---

src/conventional/commits.rs
src/conventional/config.rs

fix(check): do match start of line and end of line for the default scope regex

---

src/git.rs

As explained in [this comment](https://github.com/convco/convco/issues/264#issuecomment-2385447459), the #265 introduce a random result depending on the tag order.
This PR fixes it and add a unit test to avoid regression.

fix: Find last prerelease on unordered prerelease list

---

.github/workflows/release.yml
Cargo.toml

Adds cross-compilation support to the Release CI pipeline.
See commit messages of individual commits.

ci(release): add cross-compilation support

---

Cargo.toml
README.md
src/cli.rs
src/cmd.rs
src/cmd/completions.rs
src/main.rs

Add a command to generate shell completions

---

src/cmd/version.rs

fix: align bump prerelease behaviour for a repo with only pre-release tags
