convco/convco

src/conventional/commits.rs

The spec is quite vague as to what characters are allowed in a scope. It looks like the Javascript implementation is very loose (https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-commits-parser/index.js#L10) - allowing spaces, $, . and general word chars. Not sure how wide to cast it, but I had a use-case where a scope included digits and that seems fairly reasonable to allow?
Thanks for this tool, great to have a simple executable and not have to deal with npm installs!

feat: allow a scope to contain numbers

---

src/cmd/changelog.rs
src/conventional/changelog.rs

Make the commit body available in the template context, so that it can be used for more detailed release notes in custom templates.

feat(changelog): make commit body available in template context

---

Cargo.lock
Cargo.toml

Homebrew complains if the binary depends on the systems libz:
==> brew linkage --test convco/formulae/convco
==> FAILED
Unwanted system libraries:
/lib/x86_64-linux-gnu/libz.so.1

chore: enable zlib-ng-compat

---

src/cli.rs
src/cmd/changelog.rs

If a release contains no sections to display `--skip-empty` can be used to not show the release in the changelog.
This is useful if old commits were not conventional or if you configured to hide some types and the release contains no sections.
Refs: #30

feat(changelog): add skip empty flag

---

src/cmd/commit.rs

In `vim` the editor can be closed using `:wq` `:x` or `ZZ`.
The latter two will not save the buffer if nothing changed.
This should not be an issue if the author is happy with the conventional commit message and doesnot want to add a body.

fix(commit): do not require save for editor

---

src/cli.rs
src/cmd/changelog.rs
src/cmd/version.rs
src/git.rs

I was testing convco with a monorepo. I need that only the commits that update one folder to be used to calculate the next version or changelog. So I added a new argument --file (multiple) to allow filtering commits.
I don't know rust but it seems to work. I hope that it can be useful.

Support monorepo

---

.versionrc
src/cmd/commit.rs
src/conventional/commit/message.hbs
src/conventional/config.rs

A commit template can be configured in `.versionrc`:
```yaml
commitTemplate: "src/conventional/commit/message.hbs"
```
The binary contains the template at `src/conventional/commit/message.hbs`
Refs: #54

feat(commit): use template to format message

---

src/cli.rs
src/cmd/changelog.rs
src/semver.rs

Adds the following options
--max-majors <MAX_MAJORS>
Only show this number of minor versions
--max-minors <MAX_MINORS>
Only print this number of major versions
--max-patches <MAX_PATCHES>
Only show this number of patch versions
Refs: #59

feat(changelog): filter max majors/minors/patches

---

src/cli.rs
src/cmd/check.rs
src/git.rs

Adds the option: `--ignore-reverts``
If turned on, git commit messages matches on regex `(?i)revert` are ignored.
Closes https://github.com/convco/convco/issues/80
---
For example:
```
convco check origin/master..HEAD
FAIL  c790e42  first line doesn't match `<type>[optional scope]: <description>`  Revert "just a test"
convco check origin/master..HEAD --ignore-reverts
no commits checked
```

feat(check): filter commits made by git revert

---

src/cli.rs
src/cmd/changelog.rs
src/conventional/changelog.rs
src/conventional/changelog/commit.hbs
src/conventional/changelog/handlebars.rs
src/conventional/changelog/template.hbs
src/conventional/config.rs

Currently lines are wrapped based on the description only but not on the scope. Now the word-wrap is part of the template and takes the full line into account.
```hbs
{{#word-wrap}}
..
{{/word-wrap}}
```
This also add control for word wrap and line length as flags.
`--no-wrap` to disable wrapping.
`--line-length <LINE_LENGTH>` to set the line length.
Refs: #84

fix(changelog): improve word wrap and line length config/flags

---

src/main.rs

If the git repo can't be opened because of the `safe.directory` config a hint will be printed:
> Could not open the git repository.
> If run from docker set the right user id and group id.
> E.g. `docker run -u \"$(id -u):$(id -g)\" -v \"$PWD:/tmp\" --workdir /tmp --rm convco/convco`
Refs: #86

fix: improve error handling in case the git repo could not be opened

---

README.md
src/cli.rs
src/cmd.rs
src/cmd/config.rs
src/error.rs
src/main.rs

Added a sample (from defaults) versionrc-default.yaml
Updated the README.md to discuss how the configuration is loaded

feat: add cli parameter to show the default configuration

---

Cargo.lock
Cargo.toml
build.rs
release.toml
src/cli.rs
src/cmd/changelog.rs
src/cmd/check.rs
src/conventional/changelog.rs

To prepare a release one can change the Unreleased header to prepare for the next commit.
E.g.
`convco changelog -u $(convco version bump)` will create a changelog for the next version.
This feature will make it possible for release workflows to update the changelog file.
Refs: #85

feat(changelog): customize unreleased header

---

.github/workflows/pr.yml
src/cli.rs
src/cmd/changelog.rs
src/cmd/check.rs

When `--unreleased` is not a version it will not be prefixed.
Closes: #101

small fixes after release v0.3.13

---

Cargo.toml
src/cli.rs
src/cmd/version.rs
src/semver.rs

When prerelease is given as a parameter with the value 'beta', the version would look like: `x.y.z-beta.1`, if this tag is present, the next bump would be `x.y.z-beta.2`.
Fixes: #90

feat(version): allows bumping a prerelease version

---

Cargo.lock
Cargo.toml
README.md

This way it can be turned off via `cargo build --no-default-flags` which is required to link against a shared `libgit2`.
This PR also bumps `git2-rs` to link against the `1.6`  branch of `libgit2`

feat: make `zlib-ng-compat` a default feature flag

---

src/cmd/changelog.rs
src/cmd/check.rs
src/cmd/version.rs
src/conventional/commits.rs
src/conventional/config.rs

resolve: #133 
Hi I have implemented a feature to strip a regex pattern from the commit message before parsing the the message. 
Currently this works via config file, however, I would like to have it as flag as well, but didnt manage to get it working as excepted. When defining the flags as clap options they would not be used for some reason. Perhaps the default value from the config would overwrite them. 
As I am not familar with rust, I copied what I saw for other options. So please review careful and let me know if there is any issue.

feat: strip prefix regex

---

src/cmd/commit.rs

To avoid forgetting to commit unstaged changes, commit will run `git add -N && git add -p` before showing the wizzard.
Refs: #146

feat(commit): intend to add and patch unstaged changes

---

Cargo.lock
Cargo.toml
src/cli.rs
src/cmd/version.rs
src/git.rs

Print out the commit sha of the version when running `convco version --commit-sha`
Refs: #156

feat(version): display commit-sha of the version

---

README.md
src/cli.rs
src/cmd/changelog.rs
src/cmd/check.rs
src/cmd/commit.rs
src/conventional/commits.rs
src/error.rs

This save the convco commit message to a file `.git/convco_msg`. In case a pre-commit hook failed, the next run of `convco commit` would recover from this file. `convco commit` can now also be used as a git editor. In this case git will call convco commit and not the other way around.
Refs: #157

feat(commit): save message to a file to recover or use as a git editor

---

src/cmd/commit.rs

This will support navigating with keys when using convco commit.
Refs: #197

fix(commit): use interact_text for text input

---

.github/workflows/release-cargo.yml

This adds a manual workflow to run cargo-release.
A changelog will be created, the crate will be published and a tag will be created.
The release workflow will trigger as a new tag is created.
Refs: #143

ci: add release-cargo workflow

---

src/cmd/changelog.rs
src/conventional.rs
src/conventional/commits.rs

keep newline in multiline footers and fix double BREAKING CHANGE BREAKING-CHANGE headers in changelog

---

Cargo.lock
Cargo.toml
src/cmd/commit.rs

This PR changes the `dialoguer::Select` to `dialoguer::FuzzySelect` and enables the `fuzzy-select` feature. 
The rationale for this change is to allow quicker developer workflow by allowing the developer to type the partial commit type and quickly select it without taking the hands off his keyboard to use the arrow keys.
This change shouldn't brake any current developer workflows, since the commit type can still be selected using the arrow keys.

feat: Use FuzzySelect for selecting type

---

src/cli.rs
src/cmd/changelog.rs
src/cmd/version.rs
src/git.rs

To ignore prerelease tags on the PR branches when compiling the final changelog after the merge, this allows to ignore prerelease tags entirely.

feat: allow to ignore prereleases when determining the last version

---

src/cmd/changelog.rs
src/conventional/changelog.rs

The current implementation links to compare URLs that refer to `HEAD`. This is not useful (in our case) as the content of this will change with future commits and does not reflect the state at the time of changelog generation.
I am not sure if there are use cases where the links using `HEAD` are meaningful. Do you want me to add an option to enable resolving to the commit ID or should this be the default/only option?

feat!: link to commit hash instead of HEAD in compareUrl

---

src/cmd/version.rs

Before this change version 0.1.0 could not have a prerelease label.

fix(version): do not ignore prerelease flag if no versions exist

---

src/cmd/version.rs
src/git.rs

Before if a tag was made on a branch that has been rebased later the bumped version for a new prerelease did conflict with the previous tag.
Here is an example of a commit graph where it went wrong. Now convco would print 1.1.0-rc.2
❯ git log --oneline --decorate --all --graph
* 6d8cd28 (HEAD -> rc) feat: release 1.1.0
*   3a9f9f0 (tag: v1.0.1, main) Merge branch 'hotfix'
|\
| * ae61e0e (tag: v1.0.1-hotfix.1, hotfix) fix: release 1.0.1-hotfix
|/
| * bb3fed9 (tag: v1.1.0-rc.1) feat: release 1.1.0
|/
* e4808fe (tag: v1.0.0) feat: release 1.0.0
❯ convco version
1.0.1
❯ convco version --bump --prerelease rc
1.1.0-rc.1
Refs: #264

fix(version): after a rebase a prerelease version should still increment

---

src/cmd/version.rs
src/git.rs

Closes #284 
In order to do not re-tag prerelease for the same channel referencing the same commit.
I created a new function `find_last_prerelease` in `git.rs`, but changing `find_last_prerelease` could be a good solution too.
Let me know if you prefer another implementation.

feat: Find matching prerelease before bumping a new one

---

Cargo.lock
Cargo.toml
src/cli.rs
src/cmd/version.rs
src/conventional/config.rs

To set the initial version for `convco version --bump` to something else than 0.1.0. Use `convco version --initial-bump-version 1.0.0` or set it using the environment variable `CONVCO_INITIAL_BUMP_VERSION`. It can also be added to the configuration under `initialBumpVersion`.
Refs: #290

feat(version): allow setting the initial version

---

src/cli.rs

Added env variables to accompany the following cli options:
- `--major` => `CONVCO_FORCE_MAJOR_BUMP`
- `--minor` => `CONVCO_FORCE_MINOR_BUMP`
- `--patch` => `CONVCO_FORCE_PATCH_BUMP`
closes #319

feat(version): add env variable for --major, --minor and --patch options
